---
title: Windows 95 Master
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:year:month:day/:title"
url: 
baseurl: "/project"
name: Your Site Name
description: Your description here
google_verification: 
include:
- ".htaccess"
exclude:
- README.md
- LICENSE
sass:
  style: :compressed
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
